//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= LicenseScout Cookbook

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4


== Tweaking the set of artifacts that appear in the license report

Usually, you want only third-party artifacts in your license report, but exclude your own artifacts.
This can be achieved by two means:

1. Vendor names to exclude
2. Global filters

=== Using Vendor names to exclude artifacts

TODO

=== Using global filters to exclude artifacts

TODO


== Documenting manually researched Licenses

Once you have researched Licenses of an artifact manually, it is also
necessary to document the findings in a structured way.
It may be after years that some legal department is asking why you came to the idea that
a certain artifact has a certain license. So it is required to:

* have the documentation structured in a way that it is easily possible to find the information on a certain version of a certain artifact.
* have the information in a permanent storage
* rely on information sources that can be verified after a long time

The original authors of the LicenseScout use a GIT repository to store the information. The repository has a simple structure:
the top-level directories are the names of the artifact as detected by the LicensScout.
the second level directories are the version numbers of the artifact as detected by the LiceseScout
In some cases where the filename contains a version number, but we have sub-directories for different versions anyway, we leave out the version number from the top-level directory.

TODO: more description

=== Querying the database

TODO: SQL examples
