language: java
jdk:
  - openjdk11
env:
  matrix:
    - TYPE=test
    - TYPE=check

cache:
  directories:
    - $HOME/.m2

before_install:
  - cd org.aposin.licensescout.core
install:
  - mvn -DskipTests=true -Dmaven.javadoc.skip=true install

script:
  - if [[ $TYPE == test ]]; then
      mvn test;
    elif [[ $TYPE == check ]]; then
      mvn license:check;
    else
      echo "$TYPE type not recognized";
      exit 1;
    fi

after_success:
  - if [[ $TYPE == test ]]; then bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy; fi