//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Miscellaneous

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4

== Local execution
LicenseScout can also be executed locally. Do the following:

* Do a build of LicenseScout using the launch configuration `/licensescout-core/launch/licensescout-core_clean_install.launch`
* Do a build of the license finder sample configuration using the launch configuration `/org.aposin.licensescout.configuration.sample/launch/org.aposin.licensescout.configuration.sample_clean_install.launch`
* Make sure the current (SNAPSHOT) version numbers of LicenseScout (from `/licensescout-core/pom.xml`) and the license finder configuration (from `/org.aposin.licensescout.configuration.sample/pom.xml`) are entered as property values in `/org.aposin.licensescout.licensereport/pom.xml`
* Run LicenseScout: `/org.aposin.licensescout.licensereport/launch/org.aposin.licensescout.licensereport_scan.launch`

