//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Alternative way of attaching license reports as artifacts

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4


Usually the generated license reports are attached as secondary artifacts to the main artifact of the module automatically.

If you have special needs regarding the attach you can disable the default attach and do it yourself using the `build-helper-maven-plugin` with the goal  https://www.mojohaus.org/build-helper-maven-plugin/attach-artifact-mojo.html[`build-helper:attach-artifact`].


.Attaching generated reports via build-helper-maven-plugin
[source, xml]
----
<properties>
  ...
	<build-helper-maven-plugin.version>3.0.0</build-helper-maven-plugin.version>
  ...
  
  <!-- Configuration related to generated License Report Result Files -->
  <licensescout.outputDirectory>${project.build.directory}</licensescout.outputDirectory>
  <licensescout.outputFilename.csv>licensereport.csv</licensescout.outputFilename.csv>
  <licensescout.outputFilename.html>licensereport.html</licensescout.outputFilename.html>
  <licensescout.outputFilename.txt>licensereport.txt</licensescout.outputFilename.txt>
  <licensereport.path.csv>${licensescout.outputDirectory}/${licensescout.outputFilename.csv}</licensereport.path.csv>
  <licensereport.path.html>${licensescout.outputDirectory}/${licensescout.outputFilename.html}</licensereport.path.html>
  <licensereport.path.txt>${licensescout.outputDirectory}/${licensescout.outputFilename.txt}</licensereport.path.txt>
  <licensereport.classifier>myclassifier</licensereport.classifier>
</properties>

...
<plugin>
  <groupId>org.aposin.licensescout</groupId>
  <artifactId>licensescout-maven-plugin</artifactId>
  <configuration>
    <attachReports>false</attachReports>    <1>
    ...
    <outputDirectory>${licensescout.outputDirectory}</outputDirectory>
    <outputs>
      <output>
        <type>CSV</type>
        <filename>${licensescout.outputFilename.csv}</filename>
      </output>
      <output>
        <type>HTML</type>
        <filename>${licensescout.outputFilename.html}</filename>
      </output>
      <output>
        <type>TXT</type>
        <filename>${licensescout.outputFilename.txt}</filename>
      </output>
    </outputs>
    ...
  </configuration>
</plugin>

<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>build-helper-maven-plugin</artifactId>
	<version>${build-helper-maven-plugin.version}</version>
    <executions>
      <execution>
        <id>attach-license-reports</id>
        <goals>
          <goal>attach-artifact</goal>
        </goals>
        <phase>verify</phase>             <2>
        <configuration>
          <artifacts>
            <artifact>
              <file>${licensereport.path.csv}</file>
              <type>csv</type>
              <classifier>${licensereport.classifier}</classifier>
            </artifact>
            <artifact>
              <file>${licensereport.path.html}</file>
              <type>html</type>
              <classifier>${licensereport.classifier}</classifier>
            </artifact>
            <artifact>
              <file>${licensereport.path.txt}</file>
              <type>txt</type>
              <classifier>${licensereport.classifier}</classifier>
            </artifact>
          </artifacts>
        </configuration>
      </execution>
    </executions>
</plugin>
----
<1> disable the automatic attach
<2> `attach-artifact` is executed in the same phase as the licensescout-maven-plugin (which is executed in `verify` by default). However in this case the order of definitions in the POM
makes sure that `build-helper-maven-plugin:attach-artifact` is executed after `licensescout-maven-plugin`.