//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Using custom report templates

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4


For HTML and TXT reports it is possible to use a custom output template.

If you want to do this, best start by making a copy of the built-in report templates
and modify them for your needs.
The built-in templates can be found in `licensescout-core/src/main/resources/templates`.
The template engine used is Velocity in version 2.1. For general information on it see:

* Velocity project: https://velocity.apache.org/
* User guide for version 2.1: https://velocity.apache.org/engine/2.1/user-guide.html

For a list of variables that are available in templates see <<../../licensescout-documentation/usermanual/configuration.adoc#report-templates>>

.Example using custom templates
[source, xml]
----
<properties>
  ...

  <!-- LicenseScout configuration -->
  <licensescout.templates.dir>src/templates</licensescout.templates.dir>
</properties>

...
<plugin>
  <groupId>org.aposin.licensescout</groupId>
  <artifactId>licensescout-maven-plugin</artifactId>
  <configuration>
    ...
    <outputs>
        <output>
            <type>HTML</type>
            <template>${licensescout.templates.dir}/custom_template_html.vm</filename> <1>
            <templateEncoding>UTF-8</templateEncoding>                                 <2>
        </output>
        <output>
            <type>TXT</type>
            <template>${licensescout.templates.dir}/custom_template_txt.vm</filename>  <3>
            <templateEncoding>UTF-8</templateEncoding>                                 <4>
        </output>
    </outputs>
    ...
  </configuration>
</plugin>
----
<1> file path to the custom template for HTML reports
<2> encoding of the custom template for HTML reports (only necessary if different from `project.build.sourceEncoding`)
<3> file path to the custom template for TXT reports
<4> encoding of the custom template for TXT reports (only necessary if different from `project.build.sourceEncoding`)

NOTE: It is currently not possible to configure custom templates as part
of a configuration bundle.
