//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Usage

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4

[source,xml]
----
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <org.aposin.licensescout.version>1.4.0-SNAPSHOT</org.aposin.licensescout.version>
  <org.aposin.licensescout.configuration.version>1.4.0-SNAPSHOT</org.aposin.licensescout.configuration.version>
  <dependenciesDirectory>${project.build.directory}/licenseScoutDependencies</dependenciesDirectory>
</properties>

<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-dependency-plugin</artifactId>
      <executions>
        <execution>
          <id>copy-dependencies</id>
          <phase>pre-site</phase>
          <goals>
            <goal>copy-dependencies</goal>
          </goals>
          <configuration>
            <outputDirectory>${dependenciesDirectory}</outputDirectory>
            <overWriteReleases>true</overWriteReleases>
            <overWriteSnapshots>true</overWriteSnapshots>
            <overWriteIfNewer>true</overWriteIfNewer>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>

<reporting>
  <plugins>
    <plugin>
      <groupId>org.aposin.licensescout</groupId>
      <artifactId>licensescout-maven-plugin</artifactId>
      <version>${org.aposin.licensescout.version}</version>
      <configuration>
        <scanDirectory>${dependenciesDirectory}</scanDirectory>
        <configurationBundle>
          <groupId>org.aposin.licensescout</groupId>
          <artifactId>org.aposin.licensescout.configuration.sample</artifactId>
          <version>${org.aposin.licensescout.configuration.version}</version>
          <classifier>configuration</classifier>
          <type>zip</type>
        </configurationBundle>
      </configuration>
    </plugin>
  </plugins>
</reporting>
----

NOTE: It is not necessary to specify an output type (like for the `licensescout-maven-plugin`). This plugin always uses a doxia renderer implicitly.
