//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Usage

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4

== Simple configuration

You basically have  to configure:

* the location to be scanned by configuring `scanDirectory`.
* the desired report output formats by giving `outputs`
* the configuration files by injecting a dependency to a configuration bundle

This will create the report output files:

* `target/licensescout/licensereport.csv`
* `target/licensescout/licensereport.html`
* `target/licensescout/licensereport.txt`

These output files are atomatically attached as secondary artifacts with
the classifier `licensereport` and the following artifact types:

* `csv` for output type `CSV`
* `htm` for output type `HTML`
* `txt` for output type `TXT`

[source,xml]
----
<plugin>
  <groupId>org.aposin.licensescout</groupId>
  <artifactId>licensescout-maven-plugin</artifactId>
  <version>1.3.0</version>
  <configuration>
  <scanDirectory>${project.build.directory}/products/my.product/win32/win32/x86/plugins/</scanDirectory>
  <outputs>
    <output>
    <type>HTML</type>
    </output>
    <output>
    <type>CSV</type>
    </output>
    <output>
    <type>TXT</type>
    </output>
  </outputs>
  </configuration>
  <executions>
  <execution>
    <goals>
    <goal>scanJava</goal>
    </goals>
  </execution>
  </executions>
  <dependencies>
  <dependency>
    <groupId>org.aposin.licensescout</groupId>
    <artifactId>org.aposin.licensescout.configuration.sample</artifactId>
    <version>1.3.0</version>
    <classifier>configuration</classifier>
    <type>zip</type>
    <scope>runtime</scope>
  </dependency>
  </dependencies>
</plugin>
----

== Configuration with database

[source,xml]
----
<plugin>
  <groupId>org.aposin.licensescout</groupId>
  <artifactId>licensescout-maven-plugin</artifactId>
  <version>1.3.0</version>
  <executions>
  <execution>
    <id>find-licenses</id>
    <phase>verify</phase>
    <goals>
        <goal>scanJava</goal>
      </goals>
      <configuration>
        <scanDirectory>${project.build.directory}/products/my.product/win32/win32/x86/plugins/</scanDirectory>
        <outputs>
          <output>
            <type>HTML</type>
            <url>${licensereport.url.html}</url>
          </output>
          <output>
            <type>CSV</type>
            <url>${licensereport.url.csv}</url>
          </output>
          <output>
            <type>TXT</type>
            <url>${licensereport.url.txt}</url>
          </output>
        </outputs>
        <licensesFilename>${licensescout-configuration.dir}/licenses.xml</licensesFilename>
        <providersFilename>${licensescout-configuration.dir}/providers.xml</providersFilename>
        <noticesFilename>${licensescout-configuration.dir}/notices.xml</noticesFilename>
        <checkedArchivesFilename>${licensescout-configuration.dir}/checkedarchives.csv</checkedArchivesFilename>
        <licenseUrlMappingsFilename>${licensescout-configuration.dir}/urlmappings.csv</licenseUrlMappingsFilename>
        <licenseNameMappingsFilename>${licensescout-configuration.dir}/namemappings.csv</licenseNameMappingsFilename>
        <globalFiltersFilename>${licensescout-configuration.dir}/globalfilters.csv</globalFiltersFilename>
        <filteredVendorNamesFilename>${licensescout-configuration.dir}/filteredvendornames.csv</filteredVendorNamesFilename>
      </configuration>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>org.aposin.licensescout</groupId>
      <artifactId>org.aposin.licensescout.configuration.sample</artifactId>
      <version>1.3.0</version>
      <classifier>configuration</classifier>
      <type>zip</type>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</plugin>
----
