//
// Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Usage

:encoding: utf-8
:lang: en
:doctype: book
:toc:
:toclevels: 4

== Simple configuration

You basically have  to configure:

* the location to be scanned by configuring `scanDirectory`.
* the configuration files by specifying a configuration bundle with `configurationBundle`
* the desired report output formats by giving `outputs`

This will create the report output files:

* `target/licensescout/licensereport.csv`
* `target/licensescout/licensereport.html`
* `target/licensescout/licensereport.txt`

These output files are atomatically attached as secondary artifacts with
the classifier `licensereport` and the following artifact types:

* `csv` for output type `CSV`
* `htm` for output type `HTML`
* `txt` for output type `TXT`

[source,xml]
----
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <org.aposin.licensescout.version>1.3.1-SNAPSHOT</org.aposin.licensescout.version>
  <org.aposin.licensescout.configuration.version>1.3.1-SNAPSHOT</org.aposin.licensescout.configuration.version>
</properties>

<plugin>
  <groupId>org.aposin.licensescout</groupId>
  <artifactId>licensescout-maven-plugin</artifactId>
  <version>${org.aposin.licensescout.version}</version>
  <configuration>
    <scanDirectory>${project.build.directory}/products/my.product/win32/win32/x86/plugins/</scanDirectory>
    <configurationBundle>
      <groupId>org.aposin.licensescout</groupId>
      <artifactId>org.aposin.licensescout.configuration.sample</artifactId>
      <version>${org.aposin.licensescout.configuration.version}</version>
      <classifier>configuration</classifier>
      <type>zip</type>
    </configurationBundle>
    <outputs>
      <output>
        <type>HTML</type>
      </output>
      <output>
        <type>CSV</type>
      </output>
      <output>
        <type>TXT</type>
      </output>
    </outputs>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>scanJava</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

== Configuration with database

[source,xml]
----
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <org.aposin.licensescout.version>1.3.1-SNAPSHOT</org.aposin.licensescout.version>
  <org.aposin.licensescout.configuration.version>1.3.1-SNAPSHOT</org.aposin.licensescout.configuration.version>
</properties>

<plugin>
  <groupId>org.aposin.licensescout</groupId>
  <artifactId>licensescout-maven-plugin</artifactId>
  <version>${org.aposin.licensescout.version}</version>
  <executions>
  <execution>
    <id>find-licenses</id>
    <phase>verify</phase>
    <goals>
        <goal>scanJava</goal>
      </goals>
      <configuration>
        <scanDirectory>${project.build.directory}/products/my.product/win32/win32/x86/plugins/</scanDirectory>
        <configurationBundle>
          <groupId>org.aposin.licensescout</groupId>
          <artifactId>org.aposin.licensescout.configuration.sample</artifactId>
          <version>${org.aposin.licensescout.configuration.version}</version>
          <classifier>configuration</classifier>
          <type>zip</type>
        </configurationBundle>
        <outputs>
          <output>
            <type>HTML</type>
            <url>${licensereport.url.html}</url>
          </output>
          <output>
            <type>CSV</type>
            <url>${licensereport.url.csv}</url>
          </output>
          <output>
            <type>TXT</type>
            <url>${licensereport.url.txt}</url>
          </output>
        </outputs>
      </configuration>
    </execution>
  </executions>
</plugin>
----
